<?xml version="1.0" encoding="utf-8"?><Database Name="SchoolsManager" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NTLZZ;Initial Catalog=SchoolsManager;Integrated Security=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="SchoolsManagerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="Stu_Code" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sub_Code" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ter_Code" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cou_Process" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cou_Exam" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cou_Score" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cou_Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Faculty" Member="Faculties">
    <Type Name="Faculty">
      <Column Name="Fac_Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fac_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="Stu_Code" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ter_Code" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pay_Money" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Pay_Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Specialization" Member="Specializations">
    <Type Name="Specialization">
      <Column Name="Spe_Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Spe_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fac_Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="Stu_Code" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Stu_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Stu_DateOfBirth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Stu_HomeTown" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Stu_Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Stu_PhoneNumber" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Stu_Religion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Stu_Ethnic" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Stu_StudyStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="Tea_Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tea_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tea_DateOfBirth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Tea_HomeTown" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Tea_Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Tea_PhoneNumber" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Tea_Religion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tea_Ethnic" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TeacherFaculty" Member="TeacherFaculties">
    <Type Name="TeacherFaculty">
      <Column Name="Tea_Code" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fac_Code" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tfa_Salary" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TimeTableCourse" Member="TimeTableCourses">
    <Type Name="TimeTableCourse">
      <Column Name="Ter_Code" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sub_Code" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tea_Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ttc_Room" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Term" Member="Terms">
    <Type Name="Term">
      <Column Name="Ter_Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ter_Name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ter_Group" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ter_YearStart" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Ter_YearEnd" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Use_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Use_Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Use_PersonName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Use_DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Use_Email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Use_PhoneNumber" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Use_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentFaculty" Member="StudentFaculties">
    <Type Name="StudentFaculty">
      <Column Name="Stu_Code" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fac_Code" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Spe_Code" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sfa_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subject" Member="Subjects">
    <Type Name="Subject">
      <Column Name="Sub_Code" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sub_Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Sub_Credits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sub_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sub_FacultyCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sub_SpecializationCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sub_Coefficient" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>