#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SchoolsManager")]
	public partial class DbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCourse(Course instance);
    partial void UpdateCourse(Course instance);
    partial void DeleteCourse(Course instance);
    partial void InsertFaculty(Faculty instance);
    partial void UpdateFaculty(Faculty instance);
    partial void DeleteFaculty(Faculty instance);
    partial void InsertPayment(Payment instance);
    partial void UpdatePayment(Payment instance);
    partial void DeletePayment(Payment instance);
    partial void InsertSpecialization(Specialization instance);
    partial void UpdateSpecialization(Specialization instance);
    partial void DeleteSpecialization(Specialization instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertTeacher(Teacher instance);
    partial void UpdateTeacher(Teacher instance);
    partial void DeleteTeacher(Teacher instance);
    partial void InsertTeacherFaculty(TeacherFaculty instance);
    partial void UpdateTeacherFaculty(TeacherFaculty instance);
    partial void DeleteTeacherFaculty(TeacherFaculty instance);
    partial void InsertTimeTableCourse(TimeTableCourse instance);
    partial void UpdateTimeTableCourse(TimeTableCourse instance);
    partial void DeleteTimeTableCourse(TimeTableCourse instance);
    partial void InsertTerm(Term instance);
    partial void UpdateTerm(Term instance);
    partial void DeleteTerm(Term instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertStudentFaculty(StudentFaculty instance);
    partial void UpdateStudentFaculty(StudentFaculty instance);
    partial void DeleteStudentFaculty(StudentFaculty instance);
    partial void InsertSubject(Subject instance);
    partial void UpdateSubject(Subject instance);
    partial void DeleteSubject(Subject instance);
    #endregion
		
		public DbDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.SchoolsManagerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Course> Courses
		{
			get
			{
				return this.GetTable<Course>();
			}
		}
		
		public System.Data.Linq.Table<Faculty> Faculties
		{
			get
			{
				return this.GetTable<Faculty>();
			}
		}
		
		public System.Data.Linq.Table<Payment> Payments
		{
			get
			{
				return this.GetTable<Payment>();
			}
		}
		
		public System.Data.Linq.Table<Specialization> Specializations
		{
			get
			{
				return this.GetTable<Specialization>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<Teacher> Teachers
		{
			get
			{
				return this.GetTable<Teacher>();
			}
		}
		
		public System.Data.Linq.Table<TeacherFaculty> TeacherFaculties
		{
			get
			{
				return this.GetTable<TeacherFaculty>();
			}
		}
		
		public System.Data.Linq.Table<TimeTableCourse> TimeTableCourses
		{
			get
			{
				return this.GetTable<TimeTableCourse>();
			}
		}
		
		public System.Data.Linq.Table<Term> Terms
		{
			get
			{
				return this.GetTable<Term>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<StudentFaculty> StudentFaculties
		{
			get
			{
				return this.GetTable<StudentFaculty>();
			}
		}
		
		public System.Data.Linq.Table<Subject> Subjects
		{
			get
			{
				return this.GetTable<Subject>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Course")]
	public partial class Course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Stu_Code;
		
		private string _Sub_Code;
		
		private int _Ter_Code;
		
		private System.Nullable<double> _Cou_Process;
		
		private System.Nullable<double> _Cou_Exam;
		
		private System.Nullable<double> _Cou_Score;
		
		private int _Cou_Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStu_CodeChanging(string value);
    partial void OnStu_CodeChanged();
    partial void OnSub_CodeChanging(string value);
    partial void OnSub_CodeChanged();
    partial void OnTer_CodeChanging(int value);
    partial void OnTer_CodeChanged();
    partial void OnCou_ProcessChanging(System.Nullable<double> value);
    partial void OnCou_ProcessChanged();
    partial void OnCou_ExamChanging(System.Nullable<double> value);
    partial void OnCou_ExamChanged();
    partial void OnCou_ScoreChanging(System.Nullable<double> value);
    partial void OnCou_ScoreChanged();
    partial void OnCou_StatusChanging(int value);
    partial void OnCou_StatusChanged();
    #endregion
		
		public Course()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Code", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Stu_Code
		{
			get
			{
				return this._Stu_Code;
			}
			set
			{
				if ((this._Stu_Code != value))
				{
					this.OnStu_CodeChanging(value);
					this.SendPropertyChanging();
					this._Stu_Code = value;
					this.SendPropertyChanged("Stu_Code");
					this.OnStu_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Code", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Sub_Code
		{
			get
			{
				return this._Sub_Code;
			}
			set
			{
				if ((this._Sub_Code != value))
				{
					this.OnSub_CodeChanging(value);
					this.SendPropertyChanging();
					this._Sub_Code = value;
					this.SendPropertyChanged("Sub_Code");
					this.OnSub_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ter_Code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ter_Code
		{
			get
			{
				return this._Ter_Code;
			}
			set
			{
				if ((this._Ter_Code != value))
				{
					this.OnTer_CodeChanging(value);
					this.SendPropertyChanging();
					this._Ter_Code = value;
					this.SendPropertyChanged("Ter_Code");
					this.OnTer_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cou_Process", DbType="Float")]
		public System.Nullable<double> Cou_Process
		{
			get
			{
				return this._Cou_Process;
			}
			set
			{
				if ((this._Cou_Process != value))
				{
					this.OnCou_ProcessChanging(value);
					this.SendPropertyChanging();
					this._Cou_Process = value;
					this.SendPropertyChanged("Cou_Process");
					this.OnCou_ProcessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cou_Exam", DbType="Float")]
		public System.Nullable<double> Cou_Exam
		{
			get
			{
				return this._Cou_Exam;
			}
			set
			{
				if ((this._Cou_Exam != value))
				{
					this.OnCou_ExamChanging(value);
					this.SendPropertyChanging();
					this._Cou_Exam = value;
					this.SendPropertyChanged("Cou_Exam");
					this.OnCou_ExamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cou_Score", DbType="Float")]
		public System.Nullable<double> Cou_Score
		{
			get
			{
				return this._Cou_Score;
			}
			set
			{
				if ((this._Cou_Score != value))
				{
					this.OnCou_ScoreChanging(value);
					this.SendPropertyChanging();
					this._Cou_Score = value;
					this.SendPropertyChanged("Cou_Score");
					this.OnCou_ScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cou_Status", DbType="Int NOT NULL")]
		public int Cou_Status
		{
			get
			{
				return this._Cou_Status;
			}
			set
			{
				if ((this._Cou_Status != value))
				{
					this.OnCou_StatusChanging(value);
					this.SendPropertyChanging();
					this._Cou_Status = value;
					this.SendPropertyChanged("Cou_Status");
					this.OnCou_StatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Faculty")]
	public partial class Faculty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fac_Code;
		
		private string _Fac_Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFac_CodeChanging(int value);
    partial void OnFac_CodeChanged();
    partial void OnFac_NameChanging(string value);
    partial void OnFac_NameChanged();
    #endregion
		
		public Faculty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fac_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Fac_Code
		{
			get
			{
				return this._Fac_Code;
			}
			set
			{
				if ((this._Fac_Code != value))
				{
					this.OnFac_CodeChanging(value);
					this.SendPropertyChanging();
					this._Fac_Code = value;
					this.SendPropertyChanged("Fac_Code");
					this.OnFac_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fac_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Fac_Name
		{
			get
			{
				return this._Fac_Name;
			}
			set
			{
				if ((this._Fac_Name != value))
				{
					this.OnFac_NameChanging(value);
					this.SendPropertyChanging();
					this._Fac_Name = value;
					this.SendPropertyChanged("Fac_Name");
					this.OnFac_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Payment")]
	public partial class Payment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Stu_Code;
		
		private int _Ter_Code;
		
		private string _Pay_Money;
		
		private int _Pay_Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStu_CodeChanging(string value);
    partial void OnStu_CodeChanged();
    partial void OnTer_CodeChanging(int value);
    partial void OnTer_CodeChanged();
    partial void OnPay_MoneyChanging(string value);
    partial void OnPay_MoneyChanged();
    partial void OnPay_StatusChanging(int value);
    partial void OnPay_StatusChanged();
    #endregion
		
		public Payment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Code", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Stu_Code
		{
			get
			{
				return this._Stu_Code;
			}
			set
			{
				if ((this._Stu_Code != value))
				{
					this.OnStu_CodeChanging(value);
					this.SendPropertyChanging();
					this._Stu_Code = value;
					this.SendPropertyChanged("Stu_Code");
					this.OnStu_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ter_Code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ter_Code
		{
			get
			{
				return this._Ter_Code;
			}
			set
			{
				if ((this._Ter_Code != value))
				{
					this.OnTer_CodeChanging(value);
					this.SendPropertyChanging();
					this._Ter_Code = value;
					this.SendPropertyChanged("Ter_Code");
					this.OnTer_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pay_Money", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Pay_Money
		{
			get
			{
				return this._Pay_Money;
			}
			set
			{
				if ((this._Pay_Money != value))
				{
					this.OnPay_MoneyChanging(value);
					this.SendPropertyChanging();
					this._Pay_Money = value;
					this.SendPropertyChanged("Pay_Money");
					this.OnPay_MoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pay_Status", DbType="Int NOT NULL")]
		public int Pay_Status
		{
			get
			{
				return this._Pay_Status;
			}
			set
			{
				if ((this._Pay_Status != value))
				{
					this.OnPay_StatusChanging(value);
					this.SendPropertyChanging();
					this._Pay_Status = value;
					this.SendPropertyChanged("Pay_Status");
					this.OnPay_StatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Specialization")]
	public partial class Specialization : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Spe_Code;
		
		private string _Spe_Name;
		
		private int _Fac_Code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSpe_CodeChanging(int value);
    partial void OnSpe_CodeChanged();
    partial void OnSpe_NameChanging(string value);
    partial void OnSpe_NameChanged();
    partial void OnFac_CodeChanging(int value);
    partial void OnFac_CodeChanged();
    #endregion
		
		public Specialization()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spe_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Spe_Code
		{
			get
			{
				return this._Spe_Code;
			}
			set
			{
				if ((this._Spe_Code != value))
				{
					this.OnSpe_CodeChanging(value);
					this.SendPropertyChanging();
					this._Spe_Code = value;
					this.SendPropertyChanged("Spe_Code");
					this.OnSpe_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spe_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Spe_Name
		{
			get
			{
				return this._Spe_Name;
			}
			set
			{
				if ((this._Spe_Name != value))
				{
					this.OnSpe_NameChanging(value);
					this.SendPropertyChanging();
					this._Spe_Name = value;
					this.SendPropertyChanged("Spe_Name");
					this.OnSpe_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fac_Code", DbType="Int NOT NULL")]
		public int Fac_Code
		{
			get
			{
				return this._Fac_Code;
			}
			set
			{
				if ((this._Fac_Code != value))
				{
					this.OnFac_CodeChanging(value);
					this.SendPropertyChanging();
					this._Fac_Code = value;
					this.SendPropertyChanged("Fac_Code");
					this.OnFac_CodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Stu_Code;
		
		private string _Stu_Name;
		
		private System.DateTime _Stu_DateOfBirth;
		
		private string _Stu_HomeTown;
		
		private string _Stu_Address;
		
		private string _Stu_PhoneNumber;
		
		private string _Stu_Religion;
		
		private string _Stu_Ethnic;
		
		private System.Nullable<int> _Stu_StudyStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStu_CodeChanging(string value);
    partial void OnStu_CodeChanged();
    partial void OnStu_NameChanging(string value);
    partial void OnStu_NameChanged();
    partial void OnStu_DateOfBirthChanging(System.DateTime value);
    partial void OnStu_DateOfBirthChanged();
    partial void OnStu_HomeTownChanging(string value);
    partial void OnStu_HomeTownChanged();
    partial void OnStu_AddressChanging(string value);
    partial void OnStu_AddressChanged();
    partial void OnStu_PhoneNumberChanging(string value);
    partial void OnStu_PhoneNumberChanged();
    partial void OnStu_ReligionChanging(string value);
    partial void OnStu_ReligionChanged();
    partial void OnStu_EthnicChanging(string value);
    partial void OnStu_EthnicChanged();
    partial void OnStu_StudyStatusChanging(System.Nullable<int> value);
    partial void OnStu_StudyStatusChanged();
    #endregion
		
		public Student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Code", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Stu_Code
		{
			get
			{
				return this._Stu_Code;
			}
			set
			{
				if ((this._Stu_Code != value))
				{
					this.OnStu_CodeChanging(value);
					this.SendPropertyChanging();
					this._Stu_Code = value;
					this.SendPropertyChanged("Stu_Code");
					this.OnStu_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Stu_Name
		{
			get
			{
				return this._Stu_Name;
			}
			set
			{
				if ((this._Stu_Name != value))
				{
					this.OnStu_NameChanging(value);
					this.SendPropertyChanging();
					this._Stu_Name = value;
					this.SendPropertyChanged("Stu_Name");
					this.OnStu_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_DateOfBirth", DbType="DateTime NOT NULL")]
		public System.DateTime Stu_DateOfBirth
		{
			get
			{
				return this._Stu_DateOfBirth;
			}
			set
			{
				if ((this._Stu_DateOfBirth != value))
				{
					this.OnStu_DateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._Stu_DateOfBirth = value;
					this.SendPropertyChanged("Stu_DateOfBirth");
					this.OnStu_DateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_HomeTown", DbType="NVarChar(MAX)")]
		public string Stu_HomeTown
		{
			get
			{
				return this._Stu_HomeTown;
			}
			set
			{
				if ((this._Stu_HomeTown != value))
				{
					this.OnStu_HomeTownChanging(value);
					this.SendPropertyChanging();
					this._Stu_HomeTown = value;
					this.SendPropertyChanged("Stu_HomeTown");
					this.OnStu_HomeTownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Address", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Stu_Address
		{
			get
			{
				return this._Stu_Address;
			}
			set
			{
				if ((this._Stu_Address != value))
				{
					this.OnStu_AddressChanging(value);
					this.SendPropertyChanging();
					this._Stu_Address = value;
					this.SendPropertyChanged("Stu_Address");
					this.OnStu_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_PhoneNumber", DbType="NVarChar(30)")]
		public string Stu_PhoneNumber
		{
			get
			{
				return this._Stu_PhoneNumber;
			}
			set
			{
				if ((this._Stu_PhoneNumber != value))
				{
					this.OnStu_PhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._Stu_PhoneNumber = value;
					this.SendPropertyChanged("Stu_PhoneNumber");
					this.OnStu_PhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Religion", DbType="NVarChar(50)")]
		public string Stu_Religion
		{
			get
			{
				return this._Stu_Religion;
			}
			set
			{
				if ((this._Stu_Religion != value))
				{
					this.OnStu_ReligionChanging(value);
					this.SendPropertyChanging();
					this._Stu_Religion = value;
					this.SendPropertyChanged("Stu_Religion");
					this.OnStu_ReligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Ethnic", DbType="NVarChar(50)")]
		public string Stu_Ethnic
		{
			get
			{
				return this._Stu_Ethnic;
			}
			set
			{
				if ((this._Stu_Ethnic != value))
				{
					this.OnStu_EthnicChanging(value);
					this.SendPropertyChanging();
					this._Stu_Ethnic = value;
					this.SendPropertyChanged("Stu_Ethnic");
					this.OnStu_EthnicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_StudyStatus", DbType="Int")]
		public System.Nullable<int> Stu_StudyStatus
		{
			get
			{
				return this._Stu_StudyStatus;
			}
			set
			{
				if ((this._Stu_StudyStatus != value))
				{
					this.OnStu_StudyStatusChanging(value);
					this.SendPropertyChanging();
					this._Stu_StudyStatus = value;
					this.SendPropertyChanged("Stu_StudyStatus");
					this.OnStu_StudyStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teacher")]
	public partial class Teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Tea_Code;
		
		private string _Tea_Name;
		
		private System.DateTime _Tea_DateOfBirth;
		
		private string _Tea_HomeTown;
		
		private string _Tea_Address;
		
		private string _Tea_PhoneNumber;
		
		private string _Tea_Religion;
		
		private string _Tea_Ethnic;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTea_CodeChanging(int value);
    partial void OnTea_CodeChanged();
    partial void OnTea_NameChanging(string value);
    partial void OnTea_NameChanged();
    partial void OnTea_DateOfBirthChanging(System.DateTime value);
    partial void OnTea_DateOfBirthChanged();
    partial void OnTea_HomeTownChanging(string value);
    partial void OnTea_HomeTownChanged();
    partial void OnTea_AddressChanging(string value);
    partial void OnTea_AddressChanged();
    partial void OnTea_PhoneNumberChanging(string value);
    partial void OnTea_PhoneNumberChanged();
    partial void OnTea_ReligionChanging(string value);
    partial void OnTea_ReligionChanged();
    partial void OnTea_EthnicChanging(string value);
    partial void OnTea_EthnicChanged();
    #endregion
		
		public Teacher()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Tea_Code
		{
			get
			{
				return this._Tea_Code;
			}
			set
			{
				if ((this._Tea_Code != value))
				{
					this.OnTea_CodeChanging(value);
					this.SendPropertyChanging();
					this._Tea_Code = value;
					this.SendPropertyChanged("Tea_Code");
					this.OnTea_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tea_Name
		{
			get
			{
				return this._Tea_Name;
			}
			set
			{
				if ((this._Tea_Name != value))
				{
					this.OnTea_NameChanging(value);
					this.SendPropertyChanging();
					this._Tea_Name = value;
					this.SendPropertyChanged("Tea_Name");
					this.OnTea_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_DateOfBirth", DbType="Date NOT NULL")]
		public System.DateTime Tea_DateOfBirth
		{
			get
			{
				return this._Tea_DateOfBirth;
			}
			set
			{
				if ((this._Tea_DateOfBirth != value))
				{
					this.OnTea_DateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._Tea_DateOfBirth = value;
					this.SendPropertyChanged("Tea_DateOfBirth");
					this.OnTea_DateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_HomeTown", DbType="NVarChar(MAX)")]
		public string Tea_HomeTown
		{
			get
			{
				return this._Tea_HomeTown;
			}
			set
			{
				if ((this._Tea_HomeTown != value))
				{
					this.OnTea_HomeTownChanging(value);
					this.SendPropertyChanging();
					this._Tea_HomeTown = value;
					this.SendPropertyChanged("Tea_HomeTown");
					this.OnTea_HomeTownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Address", DbType="NVarChar(MAX)")]
		public string Tea_Address
		{
			get
			{
				return this._Tea_Address;
			}
			set
			{
				if ((this._Tea_Address != value))
				{
					this.OnTea_AddressChanging(value);
					this.SendPropertyChanging();
					this._Tea_Address = value;
					this.SendPropertyChanged("Tea_Address");
					this.OnTea_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_PhoneNumber", DbType="NVarChar(30)")]
		public string Tea_PhoneNumber
		{
			get
			{
				return this._Tea_PhoneNumber;
			}
			set
			{
				if ((this._Tea_PhoneNumber != value))
				{
					this.OnTea_PhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._Tea_PhoneNumber = value;
					this.SendPropertyChanged("Tea_PhoneNumber");
					this.OnTea_PhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Religion", DbType="NVarChar(50)")]
		public string Tea_Religion
		{
			get
			{
				return this._Tea_Religion;
			}
			set
			{
				if ((this._Tea_Religion != value))
				{
					this.OnTea_ReligionChanging(value);
					this.SendPropertyChanging();
					this._Tea_Religion = value;
					this.SendPropertyChanged("Tea_Religion");
					this.OnTea_ReligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Ethnic", DbType="NVarChar(50)")]
		public string Tea_Ethnic
		{
			get
			{
				return this._Tea_Ethnic;
			}
			set
			{
				if ((this._Tea_Ethnic != value))
				{
					this.OnTea_EthnicChanging(value);
					this.SendPropertyChanging();
					this._Tea_Ethnic = value;
					this.SendPropertyChanged("Tea_Ethnic");
					this.OnTea_EthnicChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TeacherFaculty")]
	public partial class TeacherFaculty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Tea_Code;
		
		private int _Fac_Code;
		
		private System.Nullable<decimal> _Tfa_Salary;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTea_CodeChanging(int value);
    partial void OnTea_CodeChanged();
    partial void OnFac_CodeChanging(int value);
    partial void OnFac_CodeChanged();
    partial void OnTfa_SalaryChanging(System.Nullable<decimal> value);
    partial void OnTfa_SalaryChanged();
    #endregion
		
		public TeacherFaculty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Tea_Code
		{
			get
			{
				return this._Tea_Code;
			}
			set
			{
				if ((this._Tea_Code != value))
				{
					this.OnTea_CodeChanging(value);
					this.SendPropertyChanging();
					this._Tea_Code = value;
					this.SendPropertyChanged("Tea_Code");
					this.OnTea_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fac_Code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fac_Code
		{
			get
			{
				return this._Fac_Code;
			}
			set
			{
				if ((this._Fac_Code != value))
				{
					this.OnFac_CodeChanging(value);
					this.SendPropertyChanging();
					this._Fac_Code = value;
					this.SendPropertyChanged("Fac_Code");
					this.OnFac_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tfa_Salary", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Tfa_Salary
		{
			get
			{
				return this._Tfa_Salary;
			}
			set
			{
				if ((this._Tfa_Salary != value))
				{
					this.OnTfa_SalaryChanging(value);
					this.SendPropertyChanging();
					this._Tfa_Salary = value;
					this.SendPropertyChanged("Tfa_Salary");
					this.OnTfa_SalaryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimeTableCourse")]
	public partial class TimeTableCourse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ter_Code;
		
		private string _Sub_Code;
		
		private System.Nullable<int> _Tea_Code;
		
		private string _Ttc_Room;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTer_CodeChanging(int value);
    partial void OnTer_CodeChanged();
    partial void OnSub_CodeChanging(string value);
    partial void OnSub_CodeChanged();
    partial void OnTea_CodeChanging(System.Nullable<int> value);
    partial void OnTea_CodeChanged();
    partial void OnTtc_RoomChanging(string value);
    partial void OnTtc_RoomChanged();
    #endregion
		
		public TimeTableCourse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ter_Code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ter_Code
		{
			get
			{
				return this._Ter_Code;
			}
			set
			{
				if ((this._Ter_Code != value))
				{
					this.OnTer_CodeChanging(value);
					this.SendPropertyChanging();
					this._Ter_Code = value;
					this.SendPropertyChanged("Ter_Code");
					this.OnTer_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Code", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Sub_Code
		{
			get
			{
				return this._Sub_Code;
			}
			set
			{
				if ((this._Sub_Code != value))
				{
					this.OnSub_CodeChanging(value);
					this.SendPropertyChanging();
					this._Sub_Code = value;
					this.SendPropertyChanged("Sub_Code");
					this.OnSub_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Code", DbType="Int")]
		public System.Nullable<int> Tea_Code
		{
			get
			{
				return this._Tea_Code;
			}
			set
			{
				if ((this._Tea_Code != value))
				{
					this.OnTea_CodeChanging(value);
					this.SendPropertyChanging();
					this._Tea_Code = value;
					this.SendPropertyChanged("Tea_Code");
					this.OnTea_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ttc_Room", DbType="NChar(10)")]
		public string Ttc_Room
		{
			get
			{
				return this._Ttc_Room;
			}
			set
			{
				if ((this._Ttc_Room != value))
				{
					this.OnTtc_RoomChanging(value);
					this.SendPropertyChanging();
					this._Ttc_Room = value;
					this.SendPropertyChanged("Ttc_Room");
					this.OnTtc_RoomChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Term")]
	public partial class Term : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ter_Code;
		
		private string _Ter_Name;
		
		private string _Ter_Group;
		
		private System.DateTime _Ter_YearStart;
		
		private System.DateTime _Ter_YearEnd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTer_CodeChanging(int value);
    partial void OnTer_CodeChanged();
    partial void OnTer_NameChanging(string value);
    partial void OnTer_NameChanged();
    partial void OnTer_GroupChanging(string value);
    partial void OnTer_GroupChanged();
    partial void OnTer_YearStartChanging(System.DateTime value);
    partial void OnTer_YearStartChanged();
    partial void OnTer_YearEndChanging(System.DateTime value);
    partial void OnTer_YearEndChanged();
    #endregion
		
		public Term()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ter_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ter_Code
		{
			get
			{
				return this._Ter_Code;
			}
			set
			{
				if ((this._Ter_Code != value))
				{
					this.OnTer_CodeChanging(value);
					this.SendPropertyChanging();
					this._Ter_Code = value;
					this.SendPropertyChanged("Ter_Code");
					this.OnTer_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ter_Name", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Ter_Name
		{
			get
			{
				return this._Ter_Name;
			}
			set
			{
				if ((this._Ter_Name != value))
				{
					this.OnTer_NameChanging(value);
					this.SendPropertyChanging();
					this._Ter_Name = value;
					this.SendPropertyChanged("Ter_Name");
					this.OnTer_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ter_Group", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Ter_Group
		{
			get
			{
				return this._Ter_Group;
			}
			set
			{
				if ((this._Ter_Group != value))
				{
					this.OnTer_GroupChanging(value);
					this.SendPropertyChanging();
					this._Ter_Group = value;
					this.SendPropertyChanged("Ter_Group");
					this.OnTer_GroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ter_YearStart", DbType="Date NOT NULL")]
		public System.DateTime Ter_YearStart
		{
			get
			{
				return this._Ter_YearStart;
			}
			set
			{
				if ((this._Ter_YearStart != value))
				{
					this.OnTer_YearStartChanging(value);
					this.SendPropertyChanging();
					this._Ter_YearStart = value;
					this.SendPropertyChanged("Ter_YearStart");
					this.OnTer_YearStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ter_YearEnd", DbType="Date NOT NULL")]
		public System.DateTime Ter_YearEnd
		{
			get
			{
				return this._Ter_YearEnd;
			}
			set
			{
				if ((this._Ter_YearEnd != value))
				{
					this.OnTer_YearEndChanging(value);
					this.SendPropertyChanging();
					this._Ter_YearEnd = value;
					this.SendPropertyChanged("Ter_YearEnd");
					this.OnTer_YearEndChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Use_Name;
		
		private string _Use_Password;
		
		private string _Use_PersonName;
		
		private System.Nullable<System.DateTime> _Use_DateOfBirth;
		
		private string _Use_Email;
		
		private string _Use_PhoneNumber;
		
		private System.Nullable<int> _Use_Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUse_NameChanging(string value);
    partial void OnUse_NameChanged();
    partial void OnUse_PasswordChanging(string value);
    partial void OnUse_PasswordChanged();
    partial void OnUse_PersonNameChanging(string value);
    partial void OnUse_PersonNameChanged();
    partial void OnUse_DateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnUse_DateOfBirthChanged();
    partial void OnUse_EmailChanging(string value);
    partial void OnUse_EmailChanged();
    partial void OnUse_PhoneNumberChanging(string value);
    partial void OnUse_PhoneNumberChanged();
    partial void OnUse_StatusChanging(System.Nullable<int> value);
    partial void OnUse_StatusChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Use_Name
		{
			get
			{
				return this._Use_Name;
			}
			set
			{
				if ((this._Use_Name != value))
				{
					this.OnUse_NameChanging(value);
					this.SendPropertyChanging();
					this._Use_Name = value;
					this.SendPropertyChanged("Use_Name");
					this.OnUse_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_Password", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Use_Password
		{
			get
			{
				return this._Use_Password;
			}
			set
			{
				if ((this._Use_Password != value))
				{
					this.OnUse_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Use_Password = value;
					this.SendPropertyChanged("Use_Password");
					this.OnUse_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_PersonName", DbType="NChar(10)")]
		public string Use_PersonName
		{
			get
			{
				return this._Use_PersonName;
			}
			set
			{
				if ((this._Use_PersonName != value))
				{
					this.OnUse_PersonNameChanging(value);
					this.SendPropertyChanging();
					this._Use_PersonName = value;
					this.SendPropertyChanged("Use_PersonName");
					this.OnUse_PersonNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_DateOfBirth", DbType="DateTime")]
		public System.Nullable<System.DateTime> Use_DateOfBirth
		{
			get
			{
				return this._Use_DateOfBirth;
			}
			set
			{
				if ((this._Use_DateOfBirth != value))
				{
					this.OnUse_DateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._Use_DateOfBirth = value;
					this.SendPropertyChanged("Use_DateOfBirth");
					this.OnUse_DateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_Email", DbType="NChar(50)")]
		public string Use_Email
		{
			get
			{
				return this._Use_Email;
			}
			set
			{
				if ((this._Use_Email != value))
				{
					this.OnUse_EmailChanging(value);
					this.SendPropertyChanging();
					this._Use_Email = value;
					this.SendPropertyChanged("Use_Email");
					this.OnUse_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_PhoneNumber", DbType="NChar(50)")]
		public string Use_PhoneNumber
		{
			get
			{
				return this._Use_PhoneNumber;
			}
			set
			{
				if ((this._Use_PhoneNumber != value))
				{
					this.OnUse_PhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._Use_PhoneNumber = value;
					this.SendPropertyChanged("Use_PhoneNumber");
					this.OnUse_PhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_Status", DbType="Int")]
		public System.Nullable<int> Use_Status
		{
			get
			{
				return this._Use_Status;
			}
			set
			{
				if ((this._Use_Status != value))
				{
					this.OnUse_StatusChanging(value);
					this.SendPropertyChanging();
					this._Use_Status = value;
					this.SendPropertyChanged("Use_Status");
					this.OnUse_StatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentFaculty")]
	public partial class StudentFaculty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Stu_Code;
		
		private int _Fac_Code;
		
		private int _Spe_Code;
		
		private System.Nullable<int> _Sfa_Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStu_CodeChanging(string value);
    partial void OnStu_CodeChanged();
    partial void OnFac_CodeChanging(int value);
    partial void OnFac_CodeChanged();
    partial void OnSpe_CodeChanging(int value);
    partial void OnSpe_CodeChanged();
    partial void OnSfa_StatusChanging(System.Nullable<int> value);
    partial void OnSfa_StatusChanged();
    #endregion
		
		public StudentFaculty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Code", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Stu_Code
		{
			get
			{
				return this._Stu_Code;
			}
			set
			{
				if ((this._Stu_Code != value))
				{
					this.OnStu_CodeChanging(value);
					this.SendPropertyChanging();
					this._Stu_Code = value;
					this.SendPropertyChanged("Stu_Code");
					this.OnStu_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fac_Code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fac_Code
		{
			get
			{
				return this._Fac_Code;
			}
			set
			{
				if ((this._Fac_Code != value))
				{
					this.OnFac_CodeChanging(value);
					this.SendPropertyChanging();
					this._Fac_Code = value;
					this.SendPropertyChanged("Fac_Code");
					this.OnFac_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spe_Code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Spe_Code
		{
			get
			{
				return this._Spe_Code;
			}
			set
			{
				if ((this._Spe_Code != value))
				{
					this.OnSpe_CodeChanging(value);
					this.SendPropertyChanging();
					this._Spe_Code = value;
					this.SendPropertyChanged("Spe_Code");
					this.OnSpe_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sfa_Status", DbType="Int")]
		public System.Nullable<int> Sfa_Status
		{
			get
			{
				return this._Sfa_Status;
			}
			set
			{
				if ((this._Sfa_Status != value))
				{
					this.OnSfa_StatusChanging(value);
					this.SendPropertyChanging();
					this._Sfa_Status = value;
					this.SendPropertyChanged("Sfa_Status");
					this.OnSfa_StatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subject")]
	public partial class Subject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Sub_Code;
		
		private string _Sub_Name;
		
		private int _Sub_Credits;
		
		private int _Sub_Type;
		
		private System.Nullable<int> _Sub_FacultyCode;
		
		private System.Nullable<int> _Sub_SpecializationCode;
		
		private double _Sub_Coefficient;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSub_CodeChanging(string value);
    partial void OnSub_CodeChanged();
    partial void OnSub_NameChanging(string value);
    partial void OnSub_NameChanged();
    partial void OnSub_CreditsChanging(int value);
    partial void OnSub_CreditsChanged();
    partial void OnSub_TypeChanging(int value);
    partial void OnSub_TypeChanged();
    partial void OnSub_FacultyCodeChanging(System.Nullable<int> value);
    partial void OnSub_FacultyCodeChanged();
    partial void OnSub_SpecializationCodeChanging(System.Nullable<int> value);
    partial void OnSub_SpecializationCodeChanged();
    partial void OnSub_CoefficientChanging(double value);
    partial void OnSub_CoefficientChanged();
    #endregion
		
		public Subject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Code", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Sub_Code
		{
			get
			{
				return this._Sub_Code;
			}
			set
			{
				if ((this._Sub_Code != value))
				{
					this.OnSub_CodeChanging(value);
					this.SendPropertyChanging();
					this._Sub_Code = value;
					this.SendPropertyChanged("Sub_Code");
					this.OnSub_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Sub_Name
		{
			get
			{
				return this._Sub_Name;
			}
			set
			{
				if ((this._Sub_Name != value))
				{
					this.OnSub_NameChanging(value);
					this.SendPropertyChanging();
					this._Sub_Name = value;
					this.SendPropertyChanged("Sub_Name");
					this.OnSub_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Credits", DbType="Int NOT NULL")]
		public int Sub_Credits
		{
			get
			{
				return this._Sub_Credits;
			}
			set
			{
				if ((this._Sub_Credits != value))
				{
					this.OnSub_CreditsChanging(value);
					this.SendPropertyChanging();
					this._Sub_Credits = value;
					this.SendPropertyChanged("Sub_Credits");
					this.OnSub_CreditsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Type", DbType="Int NOT NULL")]
		public int Sub_Type
		{
			get
			{
				return this._Sub_Type;
			}
			set
			{
				if ((this._Sub_Type != value))
				{
					this.OnSub_TypeChanging(value);
					this.SendPropertyChanging();
					this._Sub_Type = value;
					this.SendPropertyChanged("Sub_Type");
					this.OnSub_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_FacultyCode", DbType="Int")]
		public System.Nullable<int> Sub_FacultyCode
		{
			get
			{
				return this._Sub_FacultyCode;
			}
			set
			{
				if ((this._Sub_FacultyCode != value))
				{
					this.OnSub_FacultyCodeChanging(value);
					this.SendPropertyChanging();
					this._Sub_FacultyCode = value;
					this.SendPropertyChanged("Sub_FacultyCode");
					this.OnSub_FacultyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_SpecializationCode", DbType="Int")]
		public System.Nullable<int> Sub_SpecializationCode
		{
			get
			{
				return this._Sub_SpecializationCode;
			}
			set
			{
				if ((this._Sub_SpecializationCode != value))
				{
					this.OnSub_SpecializationCodeChanging(value);
					this.SendPropertyChanging();
					this._Sub_SpecializationCode = value;
					this.SendPropertyChanged("Sub_SpecializationCode");
					this.OnSub_SpecializationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Coefficient", DbType="Float NOT NULL")]
		public double Sub_Coefficient
		{
			get
			{
				return this._Sub_Coefficient;
			}
			set
			{
				if ((this._Sub_Coefficient != value))
				{
					this.OnSub_CoefficientChanging(value);
					this.SendPropertyChanging();
					this._Sub_Coefficient = value;
					this.SendPropertyChanged("Sub_Coefficient");
					this.OnSub_CoefficientChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
